### ISSUE TITLE
optional "make users want to immediately start using" Requirement is too ambiguous

### ISSUE THREAD

**Issue by ericherman** [standard-for-public-code/standard-for-public-code#1015]
In "Document the code" we see:

*   Including examples that make users want to immediately start using the codebase in the documentation of the codebase is OPTIONAL.

I believe this OPTIONAL requirement is meant to encourage maintainers to create compelling examples.
However, this nearly impossible to evaluate objectively.

**Comment by ericherman** [comment]
I propose that we remove this requirement.

If we keep it, I suggest we rephrase it in terms of something we can objectively test, for instance can we see documented the _intent_ to create and maintain compelling examples.

Also, it's a very awkward sentence ( as highlighted during investigation of  #1007 ).

**Comment by Ainali** [comment]
> If we keep it, I suggest we rephrase it in terms of something we can objectively test, for instance can we see documented the _intent_ to create and maintain compelling examples.

Another way to think about it, and not only looking for documented intent, would be to say something like:

* Providing examples in the documentation for functionality mentioned in marketing is OPTIONAL.

This way, a connection between what the codebase community thinks is compelling and the examples is created and also possible to check.

**Comment by ericherman** [comment]
I like this line of thinking, if we can be clear that this is distinct from the notion that all functionality should be documented and that key functionality should include examples.

**Comment by Ainali** [comment]
Hmm, good point. the way I phrased it doesn't really add anything extra than that all functionality should be documented. Perhaps if we say that examples should be used in, or linked to from, marketing of the codebase?

**Comment by ericherman** [comment]
Perhaps the notion of _aiming for_ compelling examples which are easily grasped by new users is something that should be part of the engineering guidelines, rather than a documentation requirement _per se_.
