### ISSUE TITLE
404 on criteria links

### ISSUE THREAD

**Issue by clausmullie** [standard-for-public-code/standard-for-public-code#1036]
On the home page, under contents, the criteria links go to a 404

**Comment by clausmullie** [comment]
The links are going to 
```
https://standard-for-public-code.github.io/criteria/code-in-the-open.html
```
instead of
```
https://standard-for-public-code.github.io/standard-for-public-code/criteria/code-in-the-open.html
```

I checked the liquid and can't quite spot why
```
* [Criteria](criteria/){% assign sorted = site.pages | sort:"order" %}{% for page in sorted %}{% if page.dir == "/criteria/" %}{% if page.name != "index.md" %}{% if page.title %}
  * [{{page.title}}]({{page.url}}){% endif%}{% endif%}{% endif%}{% endfor %}
```

**Comment by clausmullie** [comment]
also works fine locally :thinking: 

so not a jekyll issue, but the github pages build omitting the /repo/ from the url for some reason?

**Comment by Ainali** [comment]
I remember similar issues before. Perhaps a baseurl in _config.yml would help? I think we did that with https://github.com/publiccodenet/publiccodenet-url-check/blob/main/_config.yml

**Comment by clausmullie** [comment]
Curious - I tried this locally and it added the baseurl to all the others links, **except** these criteria listed on the homepage

**Comment by Ainali** [comment]
Could it have anything to do with the

```
scope:
      path: '/criteria/*'
```
in_config.yml?

**Comment by clausmullie** [comment]
If I'm not mistaken, that should only be saying "for all that have /criteria/* path, show the previous and next"
https://jekyllrb.com/docs/configuration/front-matter-defaults/

**Comment by janderssonse** [comment]
With a bit of inspiration from you both @Ainali @clausmullie it should be fixed in the https://github.com/standard-for-public-code/standard-for-public-code/pull/1038
