### ISSUE TITLE
standardforpubliccode.org

### ISSUE THREAD

**Issue by jgroenen** [standard-for-public-code/standard-for-public-code#1040]
I registered "standardforpubliccode.org"; Shall I continu and set up the live site currently at https://standard-for-public-code.github.io/standard-for-public-code/ at this location?

**Comment by bvhme** [comment]
Hey Johan, please let me know if I can help with this. It is rather straightforward, however if you get stuck I can help.

**Comment by jgroenen** [comment]
OK, I made some DNS changes, added CNAME to the repo. Had to change _config bc "baseurl" was set for jekyll but not needed anymore. Did that directly on "development" branch, hope I'll be forgiven.
