### ISSUE TITLE
cibuild Process completed with exit code 6.

### ISSUE THREAD

**Issue by jgroenen** [standard-for-public-code/standard-for-public-code#1041]
Hi, I don't know what this is:

https://github.com/standard-for-public-code/standard-for-public-code/actions/runs/10324228377

**Comment by Ainali** [comment]
That looks like a temporary GitHub error. Try re-run it.

**Comment by jgroenen** [comment]
What does it do?

**Comment by Ainali** [comment]
It tests a lot of things. Is the Markdown valid, does added links work, does new files have spdx, are glossary terms used but are not linked to the glossary, are the file names well chosen, and basic spell checking.
