### ISSUE TITLE
Creating a pdf for a translation

### ISSUE THREAD

**Issue by jgroenen** [standard-for-public-code/standard-for-public-code#1051]
Hi, in this code base there is documentation for creating a printed version of the Standard for Public Code.
This is a bit under-documented I think - I was looking into using pdf.sh to create a pdf from the Dutch translation, but there are some things hard coded I think, and my weasyprint version is a bit older (which might or might not be a problem?). I thought I might just try doing the steps manually, but I'm not really sure what the proces steps are. Is it perhaps possible to describe the steps in the pdf.sh script in the /docs/printing.md file?

**Comment by Ainali** [comment]
The version shouldn't matter as one of the things the script does is checking it, and if it is too old, install a newer version.

What the script does is, in essence, build the site, make pdfs of the pages to be included and then merge all those into one big file. (It also builds an epub file, which arguably calls for a move or renaming of the script.)

**Comment by jgroenen** [comment]
Thanks, I think I will have to make some changes, to have it look at the /nl/ folder, also I think for the translation there is no checklist (right now) to compile

**Comment by ericherman** [comment]
I'm sure we could add a parameter to have it look in the correct directory. Rather than worry about that first, my suggestion is to make some changes to the script to get it to work for your immediate needs. Then we can look at how to make those changes optional, and make a pull request to add that parameter; I'm happy to help with that.

**Comment by jgroenen** [comment]
Yes, I was hacking it for now :)

What does PAGES_REPO_**NWO** stand for?

**Comment by jgroenen** [comment]
Ah, that makes sense

**Comment by ericherman** [comment]
This comment could be more verbose, or have a link to a better explanation:

https://github.com/standard-for-public-code/standard-for-public-code/blob/develop/script/serve.sh#L8-L10

It could be copy-pasted to the `pdf.sh` script as well, or if long, it could have a short comment that says, "see comment in script.sh"

**Comment by jgroenen** [comment]
I was able to generate the pdf. Had some troubles with bundle exec jekyll because of https://github.com/standard-for-public-code/community-translations-standard/issues/47
